language: python

sudo: false

matrix:
  include:
    - python: 3.8
      env: TOX_ENV='flake8'
    - python: 3.8
      env: TOX_ENV='isort'
    # Django 2.2
    - python: 3.8
      env: DJANGO='dj22' CMS='cms36'
    # Django 3.2
    - python: 3.8
      env: DJANGO='dj32' CMS='cms39'
    # Django 4.2
    - python: 3.8
      env: DJANGO='dj42' CMS='cms311'

install:
  - pip install tox coverage
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.5' ]]; then export PY_VER=py35; fi"
  - "if [[ ${DJANGO}z != 'z' ]]; then export TOX_ENV=$PY_VER-$DJANGO-$CMS; fi"

script:
  - tox -e $TOX_ENV

after_success:
  - bash <(curl -s https://codecov.io/bash)
